### ISSUE TITLE
CDSW: TypeError: attrib() got an unexpected keyword argument 'convert'

### ISSUE THREAD

**Issue by nateanth** [fastforwardlabs/cml_churn_demo_mlops#3]
When using this project in CDSW 1.8.0 and CDP PvC Base 7.1.3 (edge2ai), file 4_train_models.py errors out with:

`TypeError: attrib() got an unexpected keyword argument 'convert'
`

To fix this I needed downgrade attrs with the following command:

`pip3 install attrs==19.1.0
`

I found this solution here:
https://stackoverflow.com/questions/58189683/typeerror-attrib-got-an-unexpected-keyword-argument-convert

**Comment by nateanth** [comment]
Full error stack:

`from sklearn.model_selection import train_test_split
`
> ERROR:root:Internal Python error in the inspect module.
> Below is the traceback from this internal error.
> 
> Traceback (most recent call last):
>   File "/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-1-139cc3505715>", line 1, in <module>
>     from sklearn.model_selection import train_test_split
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/model_selection/__init__.py", line 19, in <module>
>     from ._validation import cross_val_score
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 27, in <module>
>     from ..metrics.scorer import check_scoring, _check_multimetric_scoring
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
>     from .ranking import auc
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 35, in <module>
>     from ..preprocessing import label_binarize
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
>     from ._function_transformer import FunctionTransformer
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
>     from ..utils.testing import assert_allclose_dense_sparse
>   File "/home/cdsw/.local/lib/python3.6/site-packages/sklearn/utils/testing.py", line 718, in <module>
>     import pytest
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/pytest.py", line 13, in <module>
>     from _pytest.fixtures import fixture, yield_fixture
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/_pytest/fixtures.py", line 842, in <module>
>     class FixtureFunctionMarker(object):
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
>     params = attr.ib(convert=attr.converters.optional(tuple))
> TypeError: attrib() got an unexpected keyword argument 'convert'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 1821, in showtraceback
>     stb = value._render_traceback_()
> AttributeError: 'TypeError' object has no attribute '_render_traceback_'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/core/ultratb.py", line 1132, in get_records
>     return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
>   File "/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/core/ultratb.py", line 313, in wrapped
>     return f(*args, **kwargs)
>   File "/var/lib/cdsw/python3-engine-deps/lib/python3.6/site-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
>     records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
>   File "/usr/local/lib/python3.6/inspect.py", line 1490, in getinnerframes
>     frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
>   File "/usr/local/lib/python3.6/inspect.py", line 1448, in getframeinfo
>     filename = getsourcefile(frame) or getfile(frame)
>   File "/usr/local/lib/python3.6/inspect.py", line 696, in getsourcefile
>     if getattr(getmodule(object, filename), '__loader__', None) is not None:
>   File "/usr/local/lib/python3.6/inspect.py", line 733, in getmodule
>     if ismodule(module) and hasattr(module, '__file__'):
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/py/_vendored_packages/apipkg.py", line 195, in __getattribute__
>     return getattr(getmod(), name)
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/py/_vendored_packages/apipkg.py", line 179, in getmod
>     x = importobj(modpath, None)
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
>     module = __import__(modpath, None, None, ['__doc__'])
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/pytest.py", line 13, in <module>
>     from _pytest.fixtures import fixture, yield_fixture
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/_pytest/fixtures.py", line 842, in <module>
>     class FixtureFunctionMarker(object):
>   File "/opt/cloudera/parcels/Anaconda/lib/python3.6/site-packages/_pytest/fixtures.py", line 844, in FixtureFunctionMarker
>     params = attr.ib(convert=attr.converters.optional(tuple))
> TypeError: attrib() got an unexpected keyword argument 'convert'
> TypeError: attrib() got an unexpected keyword argument 'convert'
> ---------------------------------------------------------------------------

**Comment by nateanth** [comment]
I found that upgrading pytest with the requirements.txt file to the latest available today fixed the issues I was having in CDSW.  I have not got to test this in CML yet.  

pytest==6.1.1
